-- MySQL Script generated by MySQL Workbench
-- Sat Dec 12 21:29:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL COMMENT 'Имя',
  `middle_name` VARCHAR(50) NULL COMMENT 'Отчество',
  `last_name` VARCHAR(50) NOT NULL COMMENT 'Фамилия',
  `is_male` TINYINT NOT NULL DEFAULT 1 COMMENT 'Мужчина',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`first_name` ASC, `middle_name` ASC, `last_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent` INT NULL,
  `info` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_id_fk_idx` (`parent` ASC) VISIBLE,
  CONSTRAINT `parent_id_fk`
    FOREIGN KEY (`parent`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`specialty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `info` VARCHAR(200) NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_fk_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `department_fk`
    FOREIGN KEY (`department`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT UNSIGNED NOT NULL,
  `year` YEAR(4) NOT NULL,
  `specialty` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `specialty_fk_idx` (`specialty` ASC) VISIBLE,
  CONSTRAINT `specialty_fk`
    FOREIGN KEY (`specialty`)
    REFERENCES `mydb`.`specialty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(20) NOT NULL COMMENT 'Номер студенческого билета',
  `person` INT NOT NULL COMMENT 'Персональные данные',
  `is_internally` TINYINT NOT NULL COMMENT 'Очное обучение',
  `group` INT NOT NULL COMMENT 'Группа',
  PRIMARY KEY (`id`),
  INDEX `group_fk_idx` (`group` ASC) VISIBLE,
  INDEX `person_fk_idx` (`person` ASC) VISIBLE,
  CONSTRAINT `person_fk`
    FOREIGN KEY (`person`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_fk`
    FOREIGN KEY (`group`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
